version = 0.1
[default.deploy.parameters]
stack_name = "etron-backend"
resolve_s3 = true
s3_prefix = "etron-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
parameter_overrides = "WorkspaceBucketName=\"amplify-dw9x9f8kcq4l4-mai-workspacesbucket784af028-tyhgap5jppje\" AppConfigurationBucketName=\"amplify-dw9x9f8kcq4l4-mai-appconfigurationbucket22-knsnj7tf8mls\" AthenaDatabaseName=\"etron_day_book_db\" AuditQueueArn=\"arn:aws:sqs:ap-southeast-2:890890989607:AuditQueue\" AuditQueueUrl=\"https://sqs.ap-southeast-2.amazonaws.com/890890989607/AuditQueue\" AppSyncUrl=\"https://hvcdfdjxljfkvkfs5j54zqntxa.appsync-api.ap-southeast-2.amazonaws.com/graphql\" AppSyncApiKey=\"da2-vqjtjsbaqbh55bdxpabzufnqhy\" UserPoolArn=\"arn:aws:cognito-idp:ap-southeast-2:890890989607:userpool/ap-southeast-2_d2Jecy0b9\""


[default.global.parameters]
region = "ap-southeast-2"
[dev.deploy.parameters]
stack_name = "etron-backend"
resolve_s3 = true
s3_prefix = "etron-backend"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
